version: '3.1'
services:

    db-manager-web-api:
        build:
            context: .
            dockerfile: Infra/DbManager.Infra.WebApi/Dockerfile
        image: "dbmanager/webapi:1.0"
        container_name: db-manager-web-api
        restart: always
        ports:
            - "8080:80"
        environment:
            LOG_LEVEL: "DEBUG"
        depends_on:
            - sql-server

    sql-server:
        image: "mcr.microsoft.com/mssql/server:2017-latest"
        container_name: sql-server
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "16F74A6C-F89D-4306-BD13-C972A86DE213"
            ACCEPT_EULA: "Y"
